### ISSUE TITLE
Add Day for Loan or Remove Comma from "December, 2015"

### ISSUE THREAD

**Issue by MappingKat** [MappingKat/issues#11]
<img width="382" alt="screenshot 2016-02-07 21 26 14" src="https://cloud.githubusercontent.com/assets/1077436/12878399/7db8b32a-cde1-11e5-99af-d7280314a4bd.png">

**Comment by imcmahon** [comment]
Grammar skills! Nice. Yeah no need to show the day. Committed a fix.
