### ISSUE TITLE
Rewrite content if owners cannot have cash out refi (explain why)

### ISSUE THREAD

**Issue by MappingKat** [MappingKat/issues#13]
<img width="600" alt="screenshot 2016-02-07 21 38 45" src="https://cloud.githubusercontent.com/assets/1077436/12878524/7d6c5da2-cde3-11e5-9263-29c4f0e6454b.png">

**Comment by imcmahon** [comment]
Good point! We're re-doing this block into a HELOC block so I added this as something to keep in mind there - https://trello.com/c/jkkwLhHo

:+1:

**Comment by MappingKat** [comment]
Great I like how you are putting in the trello link.  That will slowly get me to move over to that ;)
